### ISSUE TITLE
I won't use it

### ISSUE THREAD

**Issue by IlineI** [samzhangjy/BaiduSpider#1]
Sorry

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm/docrunner.py", line 309, in <module>
    tests = finder.find(module, module.__name__)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/doctest.py", line 932, in find
    self._find(tests, obj, name, module, source_lines, globs, {})
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/doctest.py", line 995, in _find
    globs, seen)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/doctest.py", line 1029, in _find
    globs, seen)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/doctest.py", line 982, in _find
    test = self._get_test(obj, name, module, globs, source_lines)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/doctest.py", line 1066, in _get_test
    filename, lineno)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/doctest.py", line 668, in get_doctest
    return DocTest(self.get_examples(string, name), globs,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/doctest.py", line 682, in get_examples
    return [x for x in self.parse(string, name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/doctest.py", line 644, in parse
    self._parse_example(m, name, lineno)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/doctest.py", line 714, in _parse_example
    lineno + len(source_lines))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/doctest.py", line 800, in _check_prefix
    (lineno+i+1, name, line))
ValueError: line 72 of the docstring for 2.BaiduSpider.search_web has inconsistent leading whitespace: '        - 带页码：'

Process finished with exit code 1

**Comment by samzhangjy** [comment]
Try removing the docstrings might help.

**Comment by samzhangjy** [comment]
I found the issue here, and I've submitted a new commit just now. Try it with the new code. If it still doesn't work, please reopen the issue and let me know.
