### ISSUE TITLE
搜索语句错误，或者是我不会使用

### ISSUE THREAD

**Issue by IlineI** [samzhangjy/BaiduSpider#2]
命令调用：pprint(spider.search_web(word=input('要搜索的关键词：')))

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/line/PycharmProjects/untitled/BaiduSpider-master/sousuo.py", line 8, in <module>
    pprint(spider.search_web(word=input('要搜索的关键词：')))

TypeError: search_web() got an unexpected keyword argument 'word'

正常调用
pprint(spider.search_web('问题'))
pprint(spider.search_pic('问题'))
pprint(spider.search_web(input('请输入问题')))
pprint(spider.search_pic(input('请输入问题')))

**Comment by samzhangjy** [comment]
你好，这应该是我的文档中没有更新参数名，把参数名从word变为query就可以了。我回头更改一下文档，有问题随时提issue。谢谢！

Sam Zhang

________________________________

**Comment by IlineI** [comment]
感谢
