### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by IlineI** [samzhangjy/BaiduSpider#3]
pprint(spider.search_video(input('')))

输入内容带有loli，就会崩溃
loli
lolita
萝莉
咯哩
洛丽塔
等等

**Comment by IlineI** [comment]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/line/PycharmProjects/untitled/BaiduSpider-master/sousuo.py", line 11, in <module>
    pprint(spider.search_video(input('')))
  File "/Users/line/PycharmProjects/untitled/BaiduSpider-master/main.py", line 629, in search_video
    pages_ = wrap.findAll('a', class_='filter-item')[1:-1]
AttributeError: 'NoneType' object has no attribute 'findAll'

**Comment by IlineI** [comment]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/line/PycharmProjects/untitled/BaiduSpider-master/sousuo.py", line 11, in <module>
    pprint(spider.search_video(input('')))
  File "/Users/line/PycharmProjects/untitled/BaiduSpider-master/main.py", line 636, in search_video
    'total': max(pages)
ValueError: max() arg is an empty sequence

**Comment by IlineI** [comment]
我只找到这一个关键词

**Comment by samzhangjy** [comment]
谢谢，我一会看一下

**Comment by samzhangjy** [comment]
这个bug已经修复了，可以clone最新的commit查看，谢谢提出！
